### ISSUE TITLE
Not all attributes are shown

### ISSUE THREAD

**Issue by bouwew** [laetificat/anna-ha#12]
Hi, I think there are several bugs in Anna, possibly in Haanna? The active preset is not shown in the attributes of the climate-entity in HA, on version 0.96.1. When I read through the code, there is a bit of code covering that.

I switched to my test-VM which is still on 0.94, the climate.anna_thermostat shows the following attributes:
```
current_temperature: 22.8
min_temp: 4
max_temp: 30
temperature: 19.5
hold_mode: asleep
friendly_name: Anna Thermostat
icon: mdi:thermometer
supported_features: 257
```

On 0.96.1, these are shown:
```
hvac_modes: heat,auto,off
current_temperature: 22.8
min_temp: 4
max_temp: 30
temperature: 19.5
friendly_name: Anna Thermostat
icon: mdi:thermometer
supported_features: 1
```

When looking through the code, both old and new, some attributes seem to be missing, on 0.96.1: current preset mode, hvac mode, and outdoor temperature.

Could it be that these have the status None? And the status of these attributes is not updated due to a bug in the (haanna?) code? I noticed that when the status of an attribute is None, the attribute is not shown in HA.

**Comment by CoMPaTech** [comment]
Makes sense, hold_mode doesn't exist anymore, not sure why preset_mode doesn't show though, will have a look!

**Comment by CoMPaTech** [comment]
Didn't write it accordingly - took some testing between 'live' and 'develop' machines, but it seems to work fine now.

![Screenshot](https://user-images.githubusercontent.com/5751088/61563103-36458f00-aa73-11e9-8422-0507a7607894.png)
