### ISSUE TITLE
Add the possibility to show schedules...

### ISSUE THREAD

**Issue by bouwew** [laetificat/anna-ha#13]
... when present and make it possible to switch between one or more schedules and the various hold-modes.

This is a feature-request.

**Comment by CoMPaTech** [comment]
Switching is the bigger thing, showing should be doable (should take a look which attribute should be able to conveniently hold that).

Hold_modes is back, as per #12 and forthcoming #14

**Comment by CoMPaTech** [comment]
Just a thinking note: experiment if device attributes (like `outside_temperature`) are an option for schema information.

**Comment by bouwew** [comment]
I looked at the climate constants as listed in const.py in the HA github climate-directory.

This now makes the most sense to me: we use the following hvac_modes: Heat and Auto.
Heating means the Anna thermostat is set to one of the preset_modes, with the following entity-states: heating and idle.
Auto means that a Schedule is activated.
So, when switching to Heating, the thermostat should switch to preset_mode, hopefully the Anna can be switched from Schedule-mode to the last used preset so we don't have to select a new preset_mode as well. Same idea for switching to Auto.

**Comment by bouwew** [comment]
When looking at the card, when Operation is in Heat-mode, the presets should be shown as selectables. When Operation is in Auto-mode, the available schedule(s) should be shown as selectables.

How to implement this, it will depend on how to activate and deactivate presets and schedules.

In a former job I was a systems architect, I'm always thinking about this high-level stuff :)

**Comment by CoMPaTech** [comment]
The technical side of things is 'relatively easy' as in following what the browser changes (using inspector in the browser). It does require some going back and forth and obviously changing haanna. However we must ensure we can read the state from the smile as HA won't know the correct state (it either has to assume it in general, or assume it from previously stored state - neither preferable). But I do see the path you are suggesting, I'll have another moment of tinkering with it tomorrow to figure the schedules part (haanna that is) and report back.

**Comment by CoMPaTech** [comment]
Working on it, but looking at the physical device, I can override the (still running) schedule by selecting a preset (i.e. asleep during daytime instead of away) and the schedule will pick up again. Wouldn't schedule active - "HVAC_MODE_AUTO" and schedule inactive - "HVAC_MODE_OFF" make more sense? Looking at [nest thermo](https://github.com/home-assistant/home-assistant/blob/84cf76ba3688760fc311733a3f179865f1317c67/homeassistant/components/nest/climate.py) that seems to make sense.

Adding to that analogy:
```
HVAC is HEAT or OFF (nest line 161) - translates to heating or not heating
If on schedule use HVAC_MODE_AUTO
```

I've got 2 schedules: `Normaal` and `Thermostat schedule`. We could make '(default) schedule to use' a variable in HA config :)

Activate schedule triggers
```
--data '<rules><rule id="a36b5218575a42809dc3748377d160f9"><name><![CDATA[Normaal]]></name><template id="b7ec76497c104b9689b7fc1876ddfa85" /><active>true</active></rule></rules>'
```

Deactivating that same schedule triggers
```
--data '<rules><rule id="a36b5218575a42809dc3748377d160f9"><name><![CDATA[Normaal]]></name><template id="b7ec76497c104b9689b7fc1876ddfa85" /><active>false</active></rule></rules>'
```

Anyway, making progress

**Comment by bouwew** [comment]
As I see it, the Anna has 2 modes: auto = a schedule is active and "manual" = off(not a good fit?) = a preset is active.
From my point of view the Anna is never off. Unless some takes the power away from the Smile mounted in between the Anna and the CV-heating-unit, then the Anna is really off. Same for the CV-heating unit, it is never off unless you pull "de stekker eruit".

Next, as you have in mind, and I agree, the Anna can cause the CV-heating-unit to be heating or be idle = off(here off fits better). These are not really an Anna-states but more the transferred states (from the heating-unit).
These two (transferred) states can be seen in both auto-mode and in manual-mode.

You can probably combine the 4 possible state-combinations into the 3 HVAC_MODES, but I think it will be confusing. Anyway, you are doing the dirty work, the decision is yours :)

**Comment by bouwew** [comment]
When looking at this:
```
# All activity disabled / Device is off/standby
HVAC_MODE_OFF = 'off'
```
HVAC_MODE_OFF can represent the "idle" mode that you have defined. But not the mode of Anna when a preset is active. To me that is more a 2nd AUTO-mode.

**Comment by bouwew** [comment]
So, HVAC_MODE_OFF = idle, HVAC_MODE_HEAT = heating and HVAC_MODE_AUTO means either a schedule is active or a preset, or a combination of the 2.

That means that HVAC_MODE_AUTO can be used in parallel with HVAC_MODE_OFF or HVAC_MODE_HEAT. That's probably something we don't want?

But, what I have written at the beginning of this message makes the most sense to me.
What do you think?

**Comment by bouwew** [comment]
This:
```
# The temperature is set based on a schedule, learned behavior, AI or some
# other related mechanism. User is not able to adjust the temperature
HVAC_MODE_AUTO = 'auto'
```
supports my idea, I would say. A preset can be some other related mechanism.
Problem is, the user can always manually override the set temperature, as an alternative to activating a preset. Making it even more complex. There is not really a HVAC_MODE that matches this way of controlling.
That makes the picture "complete" I think? Or is there something else that we don't have in the picture yet?

(Sorry about the amount of messages, that's how my brain works, when things get complex, I take it slow but steady :) )

**Comment by CoMPaTech** [comment]
Sidenote: Halfway through renaming Anna to Plugwise anyway :( That may cause some initial confusion but opens the road to `Adam` and `Lisa` as products. 

No problem on the messages, it's the same here :) Thinking out loud is a good way to process things IMHO. It does cause some collateral confusion though, especially as you noted.

- A schedule - when active - triggers presets
- Regardless of schedule (active/inactive) a preset can be set
- Heating (vs idling) is something that the Smile indicates to the 'whatever' heating component.

I'm working on an in-between version now ... at least showing the schedule/schema state, it does work. When disabling in the webbrowser it shows a different color (when active it turns green).
Still up is actually controlling it, though that will be a configuration directive (in `configuration.yaml`) I guess (like 'schedule to trigger' = 'Normaal' (fitting my Anna)).

![Schedule on through Plugwise APP](https://user-images.githubusercontent.com/5751088/61596369-ce25b300-ac02-11e9-9c9b-9378030d8d6a.png)
![Schedule off through Plugwise APP](https://user-images.githubusercontent.com/5751088/61596370-cebe4980-ac02-11e9-89c8-14dd2e64ec4d.png)

**Comment by CoMPaTech** [comment]
OK, the good news, I'm now able to `deactivate`/`turn_off` the schedule 'Normaal'. I've also added a schema 'Test' to make things harder/testable. But the good news is, with this bump in the road flattened we should be on home stretch. Just a short night of sleep ahead (changes IRL due) to think how to handle multiple schema's, but otherwise falling back to 'there is a schedule active with name X' might do the trick.

(It's mostly changes to haannna though, so we'll have to bump that as well as this component)

**Comment by CoMPaTech** [comment]
OK, it looks like it's mostly working - but - if at start of HA the schedule is inactive it won't know what to do. Should we just add an optional configuration directive 'presumed_schema' that holds the schedule to apply? (i.e. clicking the calandar-button on the climate device must have a schedule-name in the API).

This is how it looks like in states: (and yes, fugly retainer for previous state - didn't look up how to properly handle that HA-stule).
![Schermafbeelding 2019-07-22 om 12 07 57](https://user-images.githubusercontent.com/5751088/61624839-b0dffb80-ac79-11e9-9f44-56e32363ef86.png)

I had 'Normal' and always had the last one - added 'Test' yesterday as per comment above

**Comment by bouwew** [comment]
If I remember correctly, when I started using the Anna, there was no schema active. And the default schema was empty (I think). 

Having written this down as a first thought, what do you exactly means by this: "if at start of HA the schedule is inactive it won't know what to do"? The component does not pick up the various states correctly?

**Comment by CoMPaTech** [comment]
You can 'walk' the available schedules (that what the logic behind 'available_schemas' does) but there is no indication (and/or I didn't find it) which one was the last one to be active. As such, if you set it from auto=>off (either via HA, the app or by long-pressing the Anna) there is no clue for HA as to which schedule to activate.
Writing this, there should be ... otherwise the long-press to reactivate wouldn't work. Maybe we'll have to dig deeper into the xml.

I have a lot of cleaning to do in the code as it is now (and the forementioned rename to plugwise is there) but I'll try to make something work tonight given there is still some energy. It's basically a couple of new functions for haanna and accompanying changes in anna-ha.

**Comment by bouwew** [comment]
"As such, if you set it from auto=>off (either via HA, the app or by long-pressing the Anna) there is no clue for HA as to which schedule to activate."

Would it be possible to show the found schedules and let the user select one when he/she wants to activate a schedule? In the same way as when selecting a preset? Instead of showing Operation with the options Auto and Off. 

I'm thinking, with clever choices for the interface/HMI you can solve or work around the problem.

**Comment by CoMPaTech** [comment]
A pop-up of sorts isn't really HA-available that I see now, lets revisit the XML shizzle :)

**Comment by bouwew** [comment]
If you can get it to work in the HA card then it should be OK.
![image](https://user-images.githubusercontent.com/11290930/61630783-e3452500-ac88-11e9-8df5-02941e749d88.png)

**Comment by bouwew** [comment]
So, instead of Operation a header named Auto or Schedule and then a selection of available schedules, and None or Off. Or something similar.

**Comment by CoMPaTech** [comment]
Let's give that a try :)

**Comment by CoMPaTech** [comment]
On the 'last schema' thing ... it's `modification_date` based :(

Working on it

**Comment by CoMPaTech** [comment]
Which is true, I just switch from Normal to Test and then deactivated - works across restart of HA, it knew it was in `Test`
```
available_schemas: Test,Normaal,Thermostat schedule
active_schema: Test
previous_schema: Normaal
friendly_name: Plugwise Thermostat
```

**Comment by bouwew** [comment]
Wow, nice progress!!
Unfortunately, I will be away from home for a few days, can't support you with testing, sorry!
Back on Friday.

**Comment by CoMPaTech** [comment]
No problem ... this is a big change anyway (modifying `hanna.py` and adding the new `plugwise` as a component. The cool thing, they should run side-by-side that way :)

**Comment by CoMPaTech** [comment]
And apologies, didn't test yet if I could include the schedules in 'Operation'

**Comment by CoMPaTech** [comment]
As discussed - and again with many thanks for thinking along & outside of the box as well as testing it @bouwew! As the PR is ready (and HA's upstreaming PRs are in the making) I'll close this one ahead of the merge as we'll have to wait for PyPi availability.
