### ISSUE TITLE
Error related to code implementation, I think.

### ISSUE THREAD

**Issue by bouwew** [laetificat/anna-ha#16]
This error showed up in my log: `Updating state for climate.anna_thermostat (<class 'custom_components.anna.climate.ThermostatDevice'>) took 0.485 seconds. Please report platform to the developers at https://goo.gl/Nvioub`

The URL is of interest.

**Comment by CoMPaTech** [comment]
I just spotted the same in my development machine, weird.

**Comment by CoMPaTech** [comment]
Seems slow components reporting (as in, we should do async) - as told by another developer, smallest possible PR to HA and go from their (literally, don't bother about async - many can help out).

**Comment by bouwew** [comment]
Agree, this can be picked up once Anna is part of HA :P
