### ISSUE TITLE
Update request: when state is heating, differentiate between heating of the house and heating of tap water

### ISSUE THREAD

**Issue by bouwew** [laetificat/anna-ha#20]
The states could be "heating" and "tap water".
The Anna shows a tap-icon when tap water is being heated.

**Comment by CoMPaTech** [comment]
Can you get the XML data? 

as in: does `/core/appliances' show anything besides `heater_central` and `gateway` and `thermostat` (mine doesn't but I don't have tap water heating.

If so, `/core/domain_objects` should hold data we'd be looking for

**Comment by bouwew** [comment]
This functionality is added in the soon to add pull-request.
