### ISSUE TITLE
Create async version of Plugwise-dev

### ISSUE THREAD

**Issue by bouwew** [laetificat/anna-ha#23]
@laetificat , @CoMPaTech 
The next step in the Plugwise component development is an async-version.

I have made a first working attempt, please see https://github.com/bouwew/anna-ha

To make everything work with async I had to move all the getting-data-actions under the `update(self)` def and add the corresponding init-entries under `_init_(...)`. This bit took me some time before I understood that this was the way to get it working. For the rest I followed the examples in the HA docs and the various codes in de HA github, pretty straight-forward.

**Comment by CoMPaTech** [comment]
Nice progress @bouwew 

wrt the 0.11 release, should we already push the current -dev to HA? And do you still want to give that a try or rather have me do it?

**Comment by bouwew** [comment]
I think the 0.11 dev-release is ready for the push to HA. 
I can give it a try when you don't mind :)

Edit: on second thought, maybe I should clean up the present master-code so that it is closer to the my async-code. The implementation of async forced me to create a more structured code.
However, then the step to the async-code is quite small. So, maybe we could test the async-code somewhat more and then push that code to HA?

**Comment by CoMPaTech** [comment]
Not at all, if we mention it (your PR) on the open issue we might it get that closed as well (I can't close it)

Feel free to also list yourself in codemasters as your pulling most of the work these last weeks!

**Comment by CoMPaTech** [comment]
Just make sure you code PEP8 and parse through black (not sure, but -dev is not completely like what we have in HA now)

**Comment by bouwew** [comment]
What does "black" mean?

**Comment by CoMPaTech** [comment]
https://pypi.org/project/black/

Just a tool that reformats for you. Saves manually doing things but also you cant commit unless you blacked your code

-- 
Tom

**Comment by bouwew** [comment]
Ok, got it, thanks!

What about this bit of code in haanna:
```
    def get_active_schema_name(self, root):
        """Get active schema or determine last modified."""
        if self.is_legacy_anna(root):
            # return root.find("module/services/schedule_state/measurement")
            #                  .text =='on'
            return None
```
Should we create a final fix for this "patch"?

**Comment by CoMPaTech** [comment]
Not sure on the effect for legacy’s:(

-- 
Tom

**Comment by bouwew** [comment]
I think this should fix it:
```
    def get_active_schema_name(self, root):
        """Get active schema or determine last modified."""
        if self.is_legacy_anna(root):
            if root.find("module/services/schedule_state/measurement") is not None:
                return root.find("module/services/schedule_state/measurement")
                    .text =='on'
            return None
```

**Comment by bouwew** [comment]
Or maybe a little more clean:
```
    def get_active_schema_name(self, root):
        """Get active schema or determine last modified."""
        if self.is_legacy_anna(root):
            dummy = root.find("module/services/schedule_state/measurement")
            if dummy is not None:
                return dummy.text =='on'
            return None
```

**Comment by bouwew** [comment]
Better to stay in haanna-style:
```
    def get_active_schema_name(self, root):
        """Get active schema or determine last modified."""
        if self.is_legacy_anna(root):
            locator = "module/services/schedule_state/measurement"
            if root.find(locator) is not None:
                return root.find(locator)text =='on'
            return None
````
Also, we should make the same adaptation in `def get_schema_state(self, root):`

What do you think?

**Comment by CoMPaTech** [comment]
haanna was the style you suggested, I changed to the `locator` stuff to be more PEP8 compatible, but with black that has changed a bit. But committing to HA is only this repo (anna-ha) not directly related to haanna, as it is just the dependency. Agreed that we should make the same adaption, but watch out for (single) line length when we need to upstream.

**Comment by bouwew** [comment]
I also have a question about the above code: the function is to get the active schema_name but the result for a legacy Anna is true or false. Shouldn't the `== 'on'` not be there?

**Comment by CoMPaTech** [comment]
We might need to ask a XML-dump of some of the legacy owners, wasn't there one on the community forums?

**Comment by bouwew** [comment]
I found the dump: https://gist.github.com/plamola/9c14d83b8e5acd7e718436c4f2589fd5
There is one Thermostat schedule present, with an active false/true indication.
But, this schedule only has a cryptic id and no tag like 'zone_preset_based_on_time_and_presence_with_override'.
So, the cryptic id would need to be used to find other schema's I guess. We will definitely need help from @plamola

**Comment by bouwew** [comment]
Pull-requests were created for the points discussed, leaving the get_active_schema_names for the legacy Anna open, to be fixed in the future.
