### ISSUE TITLE
Plugwise update 3.1.11 causes ValueError: time data

### ISSUE THREAD

**Issue by Mariusthvdb** [laetificat/anna-ha#31]
After updating to the latest Plugwise firmware, I see this in the logs, and the climate intergrtion in HA isn't created:
```
2020-02-21 23:23:46 ERROR (MainThread) [homeassistant.components.climate] plugwise: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/plugwise/climate.py", line 276, in update
    self._domain_objects
  File "/usr/local/lib/python3.7/site-packages/haanna/haanna.py", line 165, in get_last_active_schema_name
    last_schema_active = self.get_last_active_name(root, rule_id)
  File "/usr/local/lib/python3.7/site-packages/haanna/haanna.py", line 552, in get_last_active_name
    schema_time = datetime.datetime.strptime(corrected, date_format)
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2020-02-20T19:16:34+0100' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```

please have a look what could be amiss?

**Comment by bouwew** [comment]
@Mariusthvdb Please update haanna to version 0.14.2 in manifest.json.
Does that solve the problem?

**Comment by Mariusthvdb** [comment]
No it doesn’t.... can I reference my community post here?

**Comment by bouwew** [comment]
Ok, yes, you can, I think. Just paste the URL of the post.

Can you please also file an issue at the Home Assistant github?
This helps accepting the pull-request with the hopefully coming fix for this issue.

**Comment by Mariusthvdb** [comment]
ok will do. done: https://github.com/home-assistant/home-assistant/issues/32080
here the community thread post: https://community.home-assistant.io/t/advice-how-to-load-sensor-info-from-plugwise-anna-thermostat-web-interface-xml/87801/162?u=mariusthvdb

**Comment by CoMPaTech** [comment]
As indicated on community - this is something with the time string parsing. My suggestion (@bouwew can you check this as well) is to modify https://github.com/laetificat/haanna/blob/master/haanna/haanna.py as indicated. Major apologies for not neatly submitting this in code, I can do tomorrow, but at least someone can have a look at my line of thinking.

Add
`from dateutil.parser import parse` to the imports, change comment on line 8 to reflect illegal xml chars (it's used for both xml parsing and the datetime)
Delete line 544 and lines 548-552 (the culprit) and replace with
`schema_time=parse(schema_date)` before the last line left (`schemas[schema_name...`)

Tested with below testscript on python3.6 and python3.7 providing good results on both date/time lines (alternating comments)

```
import datetime
import pytz
from dateutil.parser import parse

corrected='2020-02-20T19:16:34+0100'
corrected='2020-02-21T04:56:23.154+01:00''
epoch = datetime.datetime(1970, 1, 1, tzinfo=pytz.utc)
schema_time =parse(corrected)
schema_date=(schema_time - epoch).total_seconds()
print(schema_date)
```

**Comment by CoMPaTech** [comment]
See above PR as a suggestion towards 0.14.3 - @bouwew should I push merge it and push to PyPI for broader test-audience or do we want a smaller testgroup to start with? (Just my Anna without a boiler doesn't really cut it IMHO)

**Comment by bouwew** [comment]
@CoMPaTech do you have a fork with the update on github? If yes, then we can test via the manifest.json file.

**Comment by CoMPaTech** [comment]
Yup, thats the way the PR is setup: https://github.com/CoMPaTech/haanna/tree/datetime-annaha-issue31

**Comment by CoMPaTech** [comment]
(and good call)

**Comment by bouwew** [comment]
@Mariusthvdb Can you please test the update by changing this line in manifest.json: 
 "requirements": ["https://github.com/CoMPaTech/haanna/archive/datetime-annaha-issue31.zip#haanna==0.14.3"]

Sorry, I can't test anymore, I have installed an Adam yesterday...

**Comment by bouwew** [comment]
@CoMPaTech I'm testing on my Adam component, I'm getting:
`Setup failed for adam: Requirements for adam not found: ['https://github.com/bouwew/plugwise/archive/devel.zip#plugwise==0.0.37'].`

This has something to do with the new requirement `dateutil` I think?

**Comment by CoMPaTech** [comment]
let me try

**Comment by CoMPaTech** [comment]
Sincere apologies, forgot the python- before dateutil - commit in the PR corrected

**Comment by bouwew** [comment]
Yes, now it works, thanks!!

**Comment by Mariusthvdb** [comment]
yep I can see it in the states now, and even see the boiler_temperture.!

can't add it in the ui editor though but that must be an issue with the HA version, neither entities card or thermostat card are selected.
Will test later on my production system which is using yaml mode so I can do anything I want ;-)

thanks for the swift correction! very nice.

**Comment by CoMPaTech** [comment]
Tnx for checking ... @bouwew I'll push 0.14.3 to PyPi then

**Comment by CoMPaTech** [comment]
No GitHub that doesn't directly close this issue :)

**Comment by Mariusthvdb** [comment]
Can we use that in the _dev CC now? Or do we need the full github link in the manifest

**Comment by CoMPaTech** [comment]
I committed the version bump to _dev https://github.com/laetificat/anna-ha/commit/6cfe797af90f32f4fb2f7ce6d28b549db25a3486
