### ISSUE TITLE
Operation modes discussion from PR

### ISSUE THREAD

**Issue by CoMPaTech** [laetificat/anna-ha#8]
It might be a good idea to get the open discussion item from the PR into an issue.

As we'll have to align haannna and anna-ha as well as what is best practice for HASS let's make sure we do this right.

laetificat on 28 Apr  
```
Operation mode and away mode have no implementation. Using any of these options 
returns errors.

I'm not sure what operation mode is supposed to do, the HASS docs say 
"Operation mode to set temperature to. This defaults to current_operation mode
 if not set, or set incorrectly.", but isn't this already achieved by using the hold mode?

I'm also not able to set the hold mode at the moment, there is no option to
 select "home", "vacation", etc.
```

CoMPaTech on 28 Apr
```
Operation mode I was looking into to switch schedules, but it's a little more 
difficult (I know how to activate them again, but there is your custom (or more?) 
schedule and the learning schedule. Not sure though like you state if using operation
 mode for that is the best.

Hold mode can be set but the way hass-climate seems to have this done is 
using service climate.set_hold_mode.

On changing the support flags, good call - I shouldn't have left the partials in - 
but not sure either on the implementation.

Hold-mode - seems legit for home/vacation etc. - works using the service call
Operation-mode - was looking into (ab)using this for schedule on/of
Away-mode - the device supports it, but I recon me only having it put up it 
still needs to 'learn', the way the docs of plugwise state it they use geofencing 
on their app for this? (Not sure if I particularly like it)
```

CoMPaTech on 28 Apr
```
Commented these out until we have a decision on how to go from here 
(code is still in, but not advertising them)
```

CoMPaTech on 28 Apr 
```
One way could be to use 'presets' as 'operation_mode' so users can adjust it from 
the UI directly and either not bother about the schedules or move those as 
'hold_mode'. The way I read the code-comments, code-issues and some on the 
forum is that hold_mode is about retaining temperature at a set (i.e. hold) point, 
therefor our presets of Anna would align on hold_mode, right? Question would 
(or can) be, how (or if) we want to bother with being on schedule or not.
```

**Comment by bouwew** [comment]
As I understand it from manually adjusting the Anna, the schedule-mode overrides any set-mode. I see both mode icons on the screen. To active any set-mode the schedule-mode must be turned off, leaving only the selected set-mode icon on the screen.

**Comment by CoMPaTech** [comment]
Yeah, the thing is 'what is HASS-approach' ... so is the 'away/home/vacation' an operation_mode or is it a hold_mode. 
Another thing, you can have multiple schedules as well to switch things. Again which HASS-call do we use to determine things.

**Comment by plamola** [comment]
Imo, the `operation_mode` for Anna can either be `auto` or `manual`; the schedule is either active, or the manual setting takes precedence. Using `idle` as the `operation_mode` seems a bit odd, since Anna is still taking action upon a manual set temperature.

The `hold_mode` is a manual override, which disables the active schedule. The `hold_mode` can be nicely aligned with the Anna presets. 

Do I understand correctly that the newer model Anna support multiple schedules?
My 1.8.20 version only has a single schedule.

**Comment by CoMPaTech** [comment]
It looks like the XML shows two schedules (a default one and one I created), see screenshot. Using operation mode for manual/auto and hold_mode for override seems like a good way to go. 

![Schermafbeelding 2019-06-29 om 15 48 19](https://user-images.githubusercontent.com/5751088/60385063-825d6f00-9a85-11e9-937d-44863c6716dd.png)

It would mean we'd have to dig XML and check for 'last used schedule' or something to be able to switch it correctly :)

**Comment by CoMPaTech** [comment]
If we take that route it's also a 'done' for hold_modes, because that part is already included. I'll find some time (and better temperature) to dive into the XMLs more.

**Comment by CoMPaTech** [comment]
I'll adjust accordingly using https://github.com/home-assistant/home-assistant/pull/23899#issuecomment-507502787
